export const links: {[name: string]: string} = {
    discord: 'https://discord.gg/flybywire',
    docs: 'https://docs.flybywiresim.com/',
    twitch: 'https://www.twitch.tv/flybywiresimulations',
    youtube: 'https://www.youtube.com/flybywiresimulations',
    twitter: 'https://x.com/flybywiresim',
    facebook: 'https://www.facebook.com/FlyByWireSimulations/',
    opencollective: 'https://opencollective.com/flybywire',
    docsfaq: 'https://docs.flybywiresim.com/faq',
    installer: 'https://flybywirecdn.com/installer/release/FlyByWire_Installer_Setup.exe',
    efb: 'https://docs.flybywiresim.com/aircraft/common/flypados3',
    a32nx: 'https://flybywiresim.com/projects/a32nx',
    a380x: 'https://flybywiresim.com/projects/a380x',
    pressKit: 'https://github.com/flybywiresim/branding',
};
